name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      pypi_target:
        description: 'PyPI target (pypi or testpypi)'
        default: 'pypi'
        type: choice
        options:
          - pypi
          - testpypi

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Set up Python 3.11
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: "3.11"

      - name: Install build deps
        run: |
          pip install build

      - name: Build package
        run: |
          python -m build

      - name: Publish to TestPyPI
        if: ${{ inputs.pypi_target == 'testpypi' }}
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b
        with:
          repository-url: https://test.pypi.org/legacy/

      - name: Publish to PyPI
        if: ${{ inputs.pypi_target == 'pypi' || github.event_name == 'release' }}
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b
